# Generated by Django 5.1 on 2024-09-18 08:59

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0002_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
