# Generated by Django 5.1 on 2024-09-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0003_alter_user_user_data'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
