# Generated by Django 5.1 on 2024-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.TextField(default='user', max_length=50),
        ),
    ]
