# Generated by Django 5.1 on 2024-09-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0006_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.TextField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_role',
            field=models.ForeignKey(default='user', null=True, on_delete=django.db.models.deletion.PROTECT, to='cyberpolygonApp.role'),
        ),
    ]
