# Generated by Django 5.1 on 2024-10-02 08:56

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0009_user_telegram_id_user_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', martor.models.MartorField()),
            ],
        ),
    ]
