# Generated by Django 5.1 on 2024-10-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0011_post_title_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
