# Generated by Django 5.1 on 2024-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0012_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
