# Generated by Django 5.1 on 2024-10-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0014_answers_questions_tests_correctanswers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='CorrectAnswers',
            new_name='CorrectAnswer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer_test',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_test',
            new_name='question_text',
        ),
    ]