# Generated by Django 5.1 on 2024-11-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0017_answer_question_test_correctanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
