# Generated by Django 5.1 on 2024-11-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberpolygonApp', '0018_answer_is_correct_alter_test_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
    ]
